export const Types = {
  CREATE_USER: 'CREATE_USER',
  LOGIN_USER: 'LOGIN_USER',
  GET_USER_PROFILE: 'GET_USER_PROFILE',
  UPDATE_USER: 'UPDATE_USER',
  UPDATE_USER_PROFILE: 'UPDATE_USER_PROFILE',
  CANCEL_UPDATE_USER_PROFILE: 'CANCEL_UPDATE_USER_PROFILE',
  // UPDATE_USER_FIRST_AND_LASTNAME: 'UPDATE_USER_FIRST_AND_LASTNAME',
  // CANCEL_USER_FIRST_AND_LASTNAME: 'CANCEL_USER_FIRST_AND_LASTNAME'
}